onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@playwright/browser-chromium'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - prisma
  - protobufjs
  - sharp
  - unix-dgram
