// This file was generated by Prisma, and assumes you have installed the following:
// pnpm add --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

import { DATABASE_CONFIG } from './src/config/database.config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: DATABASE_CONFIG.url,
  },
});
