export enum TipoEvento {
  ALERTA_RECIBIDA = 'ALERTA_RECIBIDA',
  ALERTA_ASIGNADA = 'ALERTA_ASIGNADA',
  CONTACTO_FAMILIARES = 'CONTACTO_FAMILIARES',
  ATENCION_VICTIMA = 'ATENCION_VICTIMA',
  ALERTA_CERRADA = 'ALERTA_CERRADA',
  ALERTA_CANCELADA = 'ALERTA_CANCELADA',
  FALSA_ALERTA = 'FALSA_ALERTA',
  SOLICITUD_CANCELACION = 'SOLICITUD_CANCELACION',
}

export enum TipoEvidencia {
  FOTO = 'FOTO',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  DOCUMENTO = 'DOCUMENTO',
}
