// Tokens para inyección de dependencias del módulo compartido
export const EVENTO_REPOSITORIO_TOKEN = 'EVENTO_REPOSITORIO_TOKEN';
export const EVENTO_DOMINIO_SERVICE_TOKEN = 'EVENTO_DOMINIO_SERVICE_TOKEN';
export const GEO_SERVER_TOKEN = 'GEO_SERVER_TOKEN';
export const DEPARTAMENTOS_PORT_TOKEN = 'DEPARTAMENTOS_PORT_TOKEN';
export const UNIDADES_PORT_TOKEN = 'UNIDADES_PORT_TOKEN';
export const PERSONAL_TOKEN = 'PERSONAL_TOKEN';
export const OBTENER_FUNCIONARIO_USE_CASE = 'OBTENER_FUNCIONARIO_USE_CASE';
export const LISTAR_FUNCIONARIOS_USE_CASE = 'LISTAR_FUNCIONARIOS_USE_CASE';
