export const VICTIMA_REPOSITORIO = 'VICTIMA_REPOSITORIO';
export const ALERTA_VICTIMA_REPOSITORIO = 'ALERTA_VICTIMA_REPOSITORIO';
export const CONTACTO_EMERGENCIA_REPOSITORIO = 'CONTACTO_EMERGENCIA_REPOSITORIO';
export const MENSAJE_PORT_TOKEN = 'MENSAJE_PORT_TOKEN';
export const VERIFICAR_DENUNCIA_PORT_TOKEN = 'VERIFICAR_DENUNCIA_PORT_TOKEN';
export const CLAVES_API_PORT_TOKEN = 'CLAVES_API_PORT_TOKEN';
export const CODIGO_VALIDACION_REPOSITORIO_TOKEN = 'CODIGO_VALIDACION_REPOSITORIO_TOKEN';
export const VICTIMA_VALIDACION_DOMINIO_SERVICE = 'VICTIMA_VALIDACION_DOMINIO_SERVICE';
