// Tokens para inyección de dependencias del dominio de Alertas
export const ALERTA_REPOSITORIO_TOKEN = 'ALERTA_REPOSITORIO_TOKEN';
export const ALERTA_WEB_REPOSITORIO_TOKEN = 'ALERTA_WEB_REPOSITORIO_TOKEN';
export const EVIDENCIA_REPOSITORIO_TOKEN = 'EVIDENCIA_REPOSITORIO_TOKEN';
export const RUTA_ALERTA_REPOSITORIO_TOKEN = 'RUTA_ALERTA_REPOSITORIO_TOKEN';
export const CIERRE_ALERTA_REPOSITORIO_TOKEN = 'CIERRE_ALERTA_REPOSITORIO_TOKEN';
export const SOLICITUD_CANCELACION_REPOSITORIO_TOKEN = 'SOLICITUD_CANCELACION_REPOSITORIO_TOKEN';
export const DATOS_EXTERNOS_ATT_REPOSITORIO_TOKEN = 'DATOS_EXTERNOS_ATT_REPOSITORIO_TOKEN';
export const EVENTO_REPOSITORIO_TOKEN = 'EVENTO_REPOSITORIO_TOKEN';
export const EVENTO_DOMINIO_SERVICE_TOKEN = 'EVENTO_DOMINIO_SERVICE_TOKEN';
export const ATENCION_REPOSITORIO_TOKEN = 'ATENCION_REPOSITORIO_TOKEN';
export const ATENCION_FUNCIONARIO_REPOSITORIO_TOKEN = 'ATENCION_FUNCIONARIO_REPOSITORIO_TOKEN';
